#!/usr/bin/env node
// Static site build: data/*.json + src/ templates -> HTML pages at the repository root.
// No dependencies; run with `node tools/build.mjs`. The GitHub Pages workflow runs it on every push,
// so edits made in admin.html (which commit data/*.json) go live without a local build.
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { layout } from '../src/partials.mjs';
import { hashString } from '../src/lib/util.mjs';
import { paletteCSS, defaultPalette } from '../src/palettes.mjs';
import { homePage } from '../src/pages/home.mjs';
import { listingPage } from '../src/pages/properties.mjs';
import { propertyPage } from '../src/pages/property.mjs';
import { goldenVisaPage } from '../src/pages/golden-visa.mjs';
import { whyPage } from '../src/pages/why.mjs';
import { testimonialsPage } from '../src/pages/testimonials.mjs';
import { contactPage } from '../src/pages/contact.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const readJSON = async f => JSON.parse(await fs.readFile(path.join(root, f), 'utf8'));
const exists = f => fs.access(path.join(root, f)).then(() => true, () => false);

// Stylesheet sources live in src/css (one file per area, applied in name order); browsers get one file.
// The colours come first: generated from the palettes in src/palettes.mjs.
async function buildCSS() {
  const dir = path.join(root, 'src/css');
  const files = (await fs.readdir(dir)).filter(f => f.endsWith('.css')).sort();
  let css = '/* Generated by tools/build.mjs from src/palettes.mjs and src/css. Edit the sources, not this file. */\n';
  css += '\n/* ---- palettes (src/palettes.mjs) ---- */\n' + paletteCSS();
  for (const f of files) css += `\n/* ---- ${f} ---- */\n` + await fs.readFile(path.join(dir, f), 'utf8');
  await fs.mkdir(path.join(root, 'assets/css'), { recursive: true });
  await fs.writeFile(path.join(root, 'assets/css/site.css'), css);
}

async function assetVersion() {
  const files = ['assets/css/site.css', ...(await fs.readdir(path.join(root, 'assets/js'))).map(f => 'assets/js/' + f)];
  let all = '';
  for (const f of files) all += await fs.readFile(path.join(root, f), 'utf8').catch(() => '');
  return hashString(all);
}

// House rule: every film and every decorative image appears once on the whole site. A film counts once
// however it is referenced (poster, .mp4, .webm); the share image in <head> is metadata and not counted.
// Listing photos are excluded: a listing's photos appear wherever that listing does.
async function checkMedia(pages) {
  const uses = new Map();
  const add = (key, page) => uses.set(key, [...(uses.get(key) || []), page.path]);
  for (const page of pages) {
    const html = page.content;
    for (const v of html.matchAll(/<video\b[\s\S]*?<\/video>/g)) {
      const names = new Set([...v[0].matchAll(/(?:img\/hero|video)\/([\w-]+)\.(?:jpg|mp4|webm)/g)].map(m => m[1]));
      names.forEach(n => add(`film ${n}`, page));
    }
    const rest = html.replace(/<video\b[\s\S]*?<\/video>/g, '');
    for (const m of rest.matchAll(/(?:img\/hero|video)\/([\w-]+)\.(?:jpg|mp4|webm)/g)) add(`film ${m[1]}`, page);
    for (const m of rest.matchAll(/img\/(?:benefits|why)\/[\w.-]+\.(?:jpg|png|webp)/g)) add(m[0], page);
  }
  const twice = [...uses].filter(([, at]) => at.length > 1);
  if (twice.length) throw new Error('Media used more than once (each film and image must be unique):\n' + twice.map(([k, at]) => `  ${k}: ${at.join(', ')}`).join('\n'));
  const missing = [];
  for (const key of uses.keys()) {
    const files = key.startsWith('film ') ? ['mp4', 'webm'].map(x => `video/${key.slice(5)}.${x}`).concat(`img/hero/${key.slice(5)}.jpg`) : [key];
    for (const f of files) if (!(await exists(f))) missing.push(f);
  }
  if (missing.length) throw new Error('Media files missing:\n  ' + missing.join('\n  '));
}

async function main() {
  const site = await readJSON('data/site.json');
  const tax = await readJSON('data/taxonomy.json');
  const { properties } = await readJSON('data/properties.json');
  // Client stories appear only with the client's written consent (ticked in the admin) and a quote and name.
  const testimonials = ((await exists('data/testimonials.json')) ? (await readJSON('data/testimonials.json')).testimonials || [] : [])
    .filter(t => t.consent !== false && String(t.quote || '').trim() && String(t.name || '').trim());
  const faq = await readJSON('data/faq.json');
  await buildCSS();
  // favicon in the palette's colours: the N in the accent on the dark
  const pal = defaultPalette();
  await fs.writeFile(path.join(root, 'assets/img/favicon.svg'), `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="10" fill="${pal.dark}"/><path d="M19 46V18h3.2l17.6 21.6V18H45v28h-3.2L24.2 24.4V46z" fill="${pal.accent}"/></svg>\n`);
  const ctx = { site, tax, properties, testimonials, faq, v: await assetVersion() };

  const pages = [
    homePage(ctx),
    listingPage(ctx),
    ...properties.map(p => propertyPage(ctx, p)),
    goldenVisaPage(ctx),
    whyPage(ctx),
    testimonialsPage(ctx),
    contactPage(ctx)
  ];

  await checkMedia(pages);
  for (const page of pages) {
    await fs.writeFile(path.join(root, page.path), layout(ctx, page));
  }

  // Remove detail pages of listings that were deleted in the admin.
  const keep = new Set(pages.map(p => p.path));
  for (const f of await fs.readdir(root)) {
    if (/^property-.+\.html$/.test(f) && !keep.has(f)) await fs.unlink(path.join(root, f));
  }

  const base = site.indexable ? site.siteUrl.replace(/\/$/, '') + '/' : site.previewUrl;
  const urls = pages.map(p => `  <url><loc>${base}${p.path === 'index.html' ? '' : p.path}</loc></url>`).join('\n');
  await fs.writeFile(path.join(root, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`);
  await fs.writeFile(path.join(root, 'robots.txt'), site.indexable
    ? `User-agent: *\nAllow: /\nDisallow: /admin.html\n\nSitemap: ${base}sitemap.xml\n`
    : `# Preview build: the redesign concept is not meant to be indexed.\nUser-agent: *\nDisallow: /\n`);

  console.log(`built ${pages.length} pages (assets v=${ctx.v})`);
}

main().catch(e => { console.error(e); process.exit(1); });
